### ISSUE TITLE
how do I download static compiled tool?

### ISSUE THREAD

**Issue by complexgenome** [Yves-CHEN/DENTIST#1]
thanks for this awesome tool.

I'd be interested in using this, however, I'm unable to download it from the link provided (google drives'). It doesn't provide me an option to download or add to my drive.
I tried downloading via wget too, but failed. 

If possible, can you describe how to install or create an executable from the github code? Using make, install and other utilities.

best~

**Comment by privefl** [comment]
I'm using `https://drive.google.com/uc?export=download&id=1oUHc5HOTbTETLtq1ZtJMerKMpV4dSSC2`.

**Comment by complexgenome** [comment]
wget "https://drive.google.com/uc?export=download&id=1oUHc5HOTbTETLtq1ZtJMerKMpV4dSSC2" -O test

chmod +x text

./test

`-bash: ./test: cannot execute binary file: Exec format error
`

**Comment by privefl** [comment]
You get a .tar.gz when you download this. You need to extract the binary from the archive before using it.

**Comment by complexgenome** [comment]
Got it.
