### ISSUE TITLE
Output Headers

### ISSUE THREAD

**Issue by jerryguintivano** [Yves-CHEN/DENTIST#10]
I am using DENTIST_1.1.0.0 (premade binary). There are two files that are output, however the columns do not match what are described in the docs. Could you provide what these headers are for the two files?

Thanks!

**Comment by Yves-CHEN** [comment]
Hi Jerry,

Can you screenshot the content (first a few lines) of the files for me (
***@***.***)?

Thanks!
Wenhan

_________________________________
Wenhan Chen
