### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kheilbron** [Yves-CHEN/DENTIST#11]
Hi! I'm really eager to play around with DENTIST, but I don't have clearance to work with github repos unless they contain a license that explicitly states that it can be used by for-profit companies. I was wondering whether you would be willing to add a license (e.g. the [MIT license](https://gitlab.pasteur.fr/statistical-genetics/raiss/-/blob/master/LICENSE)) to the repo? Thanks for writing an  interesting paper!

**Comment by Yves-CHEN** [comment]
Sorry for the late reply. I am planning to do an update next week. I will put an MIT License in this update.

**Comment by kheilbron** [comment]
Fantastic! Looking forward to trying it out.

**Comment by kheilbron** [comment]
Hi! I just wanted to check in on this. Are you still intending to push an update?
