### ISSUE TITLE
Modifying summary statistics to a .gcta.cojo format

### ISSUE THREAD

**Issue by mkoromina** [Yves-CHEN/DENTIST#12]
Hi, 

This may be a simple question, but I decided to ask it nonetheless: Could you please advise us on what is the optimum way of creating stats in a .gcta.cojo format? For example, would extracting certain columns (SNP, PVAL, A1, A2, BETA, SE, N etc) from the summary stats be efficient enough or are further modifications to them required?

Thanks,
Maria

**Comment by Yves-CHEN** [comment]
Yes. You can try awk, e.g.

awk '{print $1,$2}' <summary file>
#This will output the 1st and 2nd columns. In the same way, you can then output the columns which correspond to (SNP, PVAL, A1, A2, BETA, SE, N )

**Comment by mkoromina** [comment]
Many thanks! Closing this issue as this works well!
