### ISSUE TITLE
do I need to prefilter input gwas summary statistics?

### ISSUE THREAD

**Issue by qianfeng2** [Yves-CHEN/DENTIST#19]
Dear whom it may concern,

I hope you are doing well.

I am a postdoc from IMB at UQ. Recently I plan to use your DENTIST to do QC, and get two questions. Much appreciated if you have any suggestions.

(1) I downloaded the pre-compiled DENTIST_1.2.0.0 in my mac and UQ Bunya cluster, neither of them work even I use chmod +x DENTIST_1.2.0.0. Does this indicate that I have no other option except compiling it?

(2) I have used plink --maf 0.01 --hwe 1e-10 to prefilter my reference genotype data, is it necessary to prefilter the input summary statistics with the same setting (--maf 0.01 --hwe 1e-10) as well before running DENTIST?

Thanks,
Qian

**Comment by Yves-CHEN** [comment]
Hi Qian. Thanks for your interest.
 
>  I downloaded the pre-compiled DENTIST_1.2.0.0 in my mac and UQ Bunya cluster, neither of them work even I use chmod +x DENTIST_1.2.0.0. Does this indicate that I have no other option except compiling it?
It should work well with UQ clusters. Can you show me the error message?
As a test, you can just directly use
> ./DENTIST_1.2.0.0
or 
> ldd ./DENTIST_1.2.0.0


(2) I have used plink --maf 0.01 --hwe 1e-10 to prefilter my reference genotype data, is it necessary to prefilter the input summary statistics with the same setting (--maf 0.01 --hwe 1e-10) as well before running DENTIST?

No. Just apply maf and hwe to reference data is usually enough. The problem about doing --maf on summary data is that the MAF in summary data may not be actual MAF (e.g. a summary data from a meta-analyses).

**Comment by qianfeng2** [comment]
Hi @Yves-CHEN 

Thanks very much for your help. Very helpful!

Good news: when I type ./DENTIST_1.2.0.0 on UQ cluster, it works now. I typed DENTIST_1.2.0.0(without ./) in the past, that's why it didn't work. 

Thanks again,
Qian
