### ISSUE TITLE
Question about duplicated variants

### ISSUE THREAD

**Issue by yanyul233** [Yves-CHEN/DENTIST#21]
Hi! Thanks for developing DENTIST! I have a question about option `--dup-threshold`. I was wondering how the duplicated variants are used in the software. I cannot find a description about this in the paper or README so that I want to ask it here. Thanks in advance!

**Comment by Yves-CHEN** [comment]
thanks very much for your interest. 
In the paper, we have "To improve computational stability, we do not include variants in near-perfect LD with variant i (e.g., r2 > 0.95) in the variant set to compute".

As said above, we first define which SNPs are in perfect LD based on a pre-set threshold (this --dup-threshold ) for LD correlation(r^2).
Then, only one of the SNPs is kept for DENTIST QC which provides a imputed z-score for this SNP. This  imputed z-score is then assigned to all of the SNPs which are in perfect LD with the one used for QC.

**Comment by yanyul233** [comment]
Hi @Yves-CHEN, thanks so much for the explanation. I'll close this issue.
